# This is a basic workflow to help you get started with Actions

name: Meson CI

# Controls when the workflow will run
on:
  schedule:
    - cron: '00 00 * * *'
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Update Dependencies
        # Run clang-format, fail build if changes required.
        run: sudo apt-get install clang-format meson
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Configure Meson
        #run: meson ${{github.workspace}}/build.meson
        run: meson setup builddir --backend ninja

      - name: Compile
        run: meson compile builddir && meson test builddir
        
      - name: clang-format
        # Run clang-format, fail build if changes required.
        run: clang-format -i */*.cpp */*.hpp
